title: CraftTheDocs V1.0
description: Craft your docs at MakerSpace Amiens
theme: just-the-docs

url: https://github.com/Makerspace-Amiens/CraftTheDocs-V1.0

color_scheme: custom_scheme

# Include custom CSS
sass:
  sass_dir: _sass